#!/usr/bin/sh

sxhkd &
#feh --bg-fill Documents/wallpapers/japanese-castle-cherry-blossom-mountain-digital-art-scenery-4k-wallpaper-uhdpaper.com-702@1@k.jpg &
feh --bg-fill Documents/wallpapers/wall.png
picom &
#feh --bg-scale Documents/wallpapers/win11.jpg &
# polybar right &; polybar left &; polybar center &; polybar power &; polybar windows &;
# polybar coins

polybar example &
polybar bottom &

# brightnessctl -d "kbd_backlight" set 0% # keyboard
# brightnessctl -d "apple-panel-bl" set 40% # screen
# brightnessctl -d "228200000.display-pipe.0" set 20% # F bar

bspc monitor -d I II III IV V # VI VII VIII IX X

bspc config border_width        4
bspc config window_gap          30

# bspc desktop I -a konsole -r 355x10
# bspc rule -a cava rectangle=200x200+0=0

bspc config split_ratio          1.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
#bspc config focused_border_color  "#5A3A8A"
bspc config normal_border_color "#1F222B"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
